CRITICAL - 2022-09-13 10:39:17 --> Config\Security::$csrfProtection is set to 'cookie'. Same-site attackers may bypass the CSRF protection. Please set it to 'session'.
in VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php on line 91.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(79): CodeIgniter\Shield\Authentication\Authenticators\Session->checkSecurityConfig()
 2 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(56): CodeIgniter\Shield\Authentication\Authenticators\Session->__construct(Object(CodeIgniter\Shield\Models\UserModel))
 3 VENDORPATH\codeigniter4\shield\src\Auth.php(61): CodeIgniter\Shield\Authentication\Authentication->factory('session')
 4 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(57): CodeIgniter\Shield\Auth->getAuthenticator()
 5 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(221): CodeIgniter\Shield\Collectors\Auth->getTitleDetails()
 6 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
 7 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663040356.336965, 0.6786, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
 8 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
 9 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
10 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/suppliergroup', 'after')
11 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 10:39:32 --> Config\Security::$csrfProtection is set to 'cookie'. Same-site attackers may bypass the CSRF protection. Please set it to 'session'.
in VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php on line 91.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(79): CodeIgniter\Shield\Authentication\Authenticators\Session->checkSecurityConfig()
 2 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(56): CodeIgniter\Shield\Authentication\Authenticators\Session->__construct(Object(CodeIgniter\Shield\Models\UserModel))
 3 VENDORPATH\codeigniter4\shield\src\Auth.php(61): CodeIgniter\Shield\Authentication\Authentication->factory('session')
 4 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(57): CodeIgniter\Shield\Auth->getAuthenticator()
 5 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(221): CodeIgniter\Shield\Collectors\Auth->getTitleDetails()
 6 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
 7 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663040372.381437, 0.1541, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
 8 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
 9 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
10 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('D:\\', 'after')
11 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:12:22 --> Call to undefined function App\Controllers\auth()
in APPPATH\Controllers\AuthController.php on line 24.
 1 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:14:06 --> Call to undefined function App\Controllers\auth()
in APPPATH\Controllers\AuthController.php on line 24.
 1 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:14:44 --> Undefined index: username
in VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php on line 279.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(279): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: username', 'VENDORPATH\\codeigniter4\\shield\\src\\Authentication\\Authenticators\\Session.php', 279, [...])
 2 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(130): CodeIgniter\Shield\Authentication\Authenticators\Session->recordLoginAttempt([...], false, '192.168.0.238', 'PostmanRuntime/7.29.2')
 3 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\Session->attempt([...])
 4 APPPATH\Controllers\AuthController.php(25): CodeIgniter\Shield\Auth->__call('attempt', [...])
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:17:58 --> Undefined index: username
in VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php on line 279.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(279): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: username', 'VENDORPATH\\codeigniter4\\shield\\src\\Authentication\\Authenticators\\Session.php', 279, [...])
 2 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(130): CodeIgniter\Shield\Authentication\Authenticators\Session->recordLoginAttempt([...], false, '192.168.0.238', 'PostmanRuntime/7.29.2')
 3 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\Session->attempt([...])
 4 APPPATH\Controllers\AuthController.php(25): CodeIgniter\Shield\Auth->__call('attempt', [...])
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:19:03 --> Undefined index: username
in VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php on line 279.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(279): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index: username', 'VENDORPATH\\codeigniter4\\shield\\src\\Authentication\\Authenticators\\Session.php', 279, [...])
 2 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(130): CodeIgniter\Shield\Authentication\Authenticators\Session->recordLoginAttempt([...], false, '192.168.0.238', 'PostmanRuntime/7.29.2')
 3 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\Session->attempt([...])
 4 APPPATH\Controllers\AuthController.php(25): CodeIgniter\Shield\Auth->__call('attempt', [...])
 5 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:20:06 --> The user has User Info in Session, so already logged in or in pending login state. If a logged in user logs in again with other account, the session data of the previous user will be used as the new user. Fix your code to prevent users from logging in without logging out or delete the session data. user_id: 1
in VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php on line 579.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(153): CodeIgniter\Shield\Authentication\Authenticators\Session->startLogin(Object(CodeIgniter\Shield\Entities\User))
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\Session->attempt([...])
 3 APPPATH\Controllers\AuthController.php(25): CodeIgniter\Shield\Auth->__call('attempt', [...])
 4 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:21:22 --> Call to undefined function App\Controllers\auth()
in APPPATH\Controllers\AuthController.php on line 25.
 1 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:23:06 --> The user has User Info in Session, so already logged in or in pending login state. If a logged in user logs in again with other account, the session data of the previous user will be used as the new user. Fix your code to prevent users from logging in without logging out or delete the session data. user_id: 1
in VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php on line 579.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(153): CodeIgniter\Shield\Authentication\Authenticators\Session->startLogin(Object(CodeIgniter\Shield\Entities\User))
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\Session->attempt([...])
 3 APPPATH\Controllers\AuthController.php(25): CodeIgniter\Shield\Auth->__call('attempt', [...])
 4 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:38:18 --> The user has User Info in Session, so already logged in or in pending login state. If a logged in user logs in again with other account, the session data of the previous user will be used as the new user. Fix your code to prevent users from logging in without logging out or delete the session data. user_id: 1
in VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php on line 579.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\Session.php(153): CodeIgniter\Shield\Authentication\Authenticators\Session->startLogin(Object(CodeIgniter\Shield\Entities\User))
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\Session->attempt([...])
 3 APPPATH\Controllers\AuthController.php(24): CodeIgniter\Shield\Auth->__call('attempt', [...])
 4 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:54:59 --> Undefined property: CodeIgniter\Shield\Auth::$loggedIn
in APPPATH\Controllers\AuthController.php on line 19.
 1 APPPATH\Controllers\AuthController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: CodeIgniter\\Shield\\Auth::$loggedIn', 'APPPATH\\Controllers\\AuthController.php', 19, [])
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:55:31 --> Undefined property: CodeIgniter\Shield\Auth::$loggedIn
in APPPATH\Controllers\AuthController.php on line 19.
 1 APPPATH\Controllers\AuthController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: CodeIgniter\\Shield\\Auth::$loggedIn', 'APPPATH\\Controllers\\AuthController.php', 19, [])
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:55:38 --> Undefined property: CodeIgniter\Shield\Auth::$loggedIn
in APPPATH\Controllers\AuthController.php on line 19.
 1 APPPATH\Controllers\AuthController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: CodeIgniter\\Shield\\Auth::$loggedIn', 'APPPATH\\Controllers\\AuthController.php', 19, [])
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 12:55:47 --> Undefined property: CodeIgniter\Shield\Auth::$loggedIn
in APPPATH\Controllers\AuthController.php on line 19.
 1 APPPATH\Controllers\AuthController.php(19): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: CodeIgniter\\Shield\\Auth::$loggedIn', 'APPPATH\\Controllers\\AuthController.php', 19, [])
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 13:12:34 --> Undefined property: CodeIgniter\Shield\Auth::$id
in APPPATH\Controllers\AuthController.php on line 66.
 1 APPPATH\Controllers\AuthController.php(66): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined property: CodeIgniter\\Shield\\Auth::$id', 'APPPATH\\Controllers\\AuthController.php', 66, [...])
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 13:32:55 --> Undefined variable: msg
in APPPATH\Controllers\AuthController.php on line 92.
 1 APPPATH\Controllers\AuthController.php(92): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined variable: msg', 'APPPATH\\Controllers\\AuthController.php', 92, [...])
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->logout()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 13:35:38 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('4', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663050938.799569, 0.1068, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:13:33 --> Return value of CodeIgniter\Router\RouteCollection::getFilterForRoute() must be of the type string, array returned
in SYSTEMPATH\Router\RouteCollection.php on line 1090.
 1 SYSTEMPATH\Router\Router.php(188): CodeIgniter\Router\RouteCollection->getFilterForRoute('api/v1/logout')
 2 SYSTEMPATH\CodeIgniter.php(782): CodeIgniter\Router\Router->handle('api/v1/logout')
 3 SYSTEMPATH\CodeIgniter.php(406): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:21:10 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('6', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663053670.375562, 0.0879, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:21:29 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('8', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663053689.700713, 0.0892, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:22:31 --> token is not a valid authenticator.
in VENDORPATH\codeigniter4\shield\src\Authentication\AuthenticationException.php on line 17.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(49): CodeIgniter\Shield\Authentication\AuthenticationException::forUnknownAuthenticator('token')
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(154): CodeIgniter\Shield\Authentication\Authentication->factory('token')
 3 APPPATH\Filters\CheckAuthFilter.php(29): CodeIgniter\Shield\Auth->__call('loggedIn', [])
 4 SYSTEMPATH\Filters\Filters.php(173): App\Filters\CheckAuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 5 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('api/v1/logout', 'before')
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:24:23 --> token is not a valid authenticator.
in VENDORPATH\codeigniter4\shield\src\Authentication\AuthenticationException.php on line 17.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(49): CodeIgniter\Shield\Authentication\AuthenticationException::forUnknownAuthenticator('token')
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(154): CodeIgniter\Shield\Authentication\Authentication->factory('token')
 3 APPPATH\Filters\CheckAuthFilter.php(29): CodeIgniter\Shield\Auth->__call('loggedIn', [])
 4 SYSTEMPATH\Filters\Filters.php(173): App\Filters\CheckAuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 5 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('api/v1/logout', 'before')
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:30:01 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('9', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663054200.952464, 0.0941, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:30:24 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('10', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663054224.060383, 0.0862, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:32:53 --> Argument 1 passed to CodeIgniter\Shield\Entities\User::getAccessToken() must be of the type string or null, object given, called in D:\Developer\codeigniter4-erp-clg\app\Controllers\AuthController.php on line 74
in VENDORPATH\codeigniter4\shield\src\Authentication\Traits\HasAccessTokens.php on line 76.
 1 APPPATH\Controllers\AuthController.php(74): CodeIgniter\Shield\Entities\User->getAccessToken(Object(CodeIgniter\Shield\Entities\AccessToken))
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:34:20 --> Argument 1 passed to CodeIgniter\Shield\Entities\User::getAccessToken() must be of the type string or null, object given, called in D:\Developer\codeigniter4-erp-clg\app\Controllers\AuthController.php on line 74
in VENDORPATH\codeigniter4\shield\src\Authentication\Traits\HasAccessTokens.php on line 76.
 1 APPPATH\Controllers\AuthController.php(74): CodeIgniter\Shield\Entities\User->getAccessToken(Object(CodeIgniter\Shield\Entities\AccessToken))
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:36:51 --> Cannot use object of type CodeIgniter\Shield\Entities\AccessToken as array
in APPPATH\Controllers\AuthController.php on line 74.
 1 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->login()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:55:01 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('10', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663055700.984025, 0.0854, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:55:05 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('18', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663055705.183873, 0.0851, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 14:55:11 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('18', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663055711.673327, 0.0869, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-09-13 14:55:44 --> mysqli_sql_exception: Unknown column 'productbrand.deleted_at' in 'where clause' in D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\Developer\codeigniter4-erp-clg\app\Controllers\ProductBrandController.php(27): CodeIgniter\BaseModel->findAll()
#7 D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\ProductBrandController->index()
#8 D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductBrandController))
#9 D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Developer\codeigniter4-erp-clg\public\index.php(73): CodeIgniter\CodeIgniter->run()
#11 D:\Developer\codeigniter4-erp-clg\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('D:\\Developer\\co...')
#12 {main}
CRITICAL - 2022-09-13 14:55:44 --> Unknown column 'productbrand.deleted_at' in 'where clause'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT *
FROM `productbrand`
WHERE `productbrand`.`deleted_at` IS NULL', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *
FROM `productbrand`
WHERE `productbrand`.`deleted_at` IS NULL')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *
FROM `productbrand`
WHERE `productbrand`.`deleted_at` IS NULL')
 4 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `productbrand`
WHERE `productbrand`.`deleted_at` IS NULL', [], false)
 5 SYSTEMPATH\Model.php(223): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
 7 APPPATH\Controllers\ProductBrandController.php(27): CodeIgniter\BaseModel->findAll()
 8 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\ProductBrandController->index()
 9 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\ProductBrandController))
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:21:38 --> token is not a valid authenticator.
in VENDORPATH\codeigniter4\shield\src\Authentication\AuthenticationException.php on line 17.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(49): CodeIgniter\Shield\Authentication\AuthenticationException::forUnknownAuthenticator('token')
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(154): CodeIgniter\Shield\Authentication\Authentication->factory('token')
 3 APPPATH\Filters\CheckAuthFilter.php(29): CodeIgniter\Shield\Auth->__call('loggedIn', [])
 4 SYSTEMPATH\Filters\Filters.php(173): App\Filters\CheckAuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 5 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('api/v1/supplier/SP-00000000001', 'before')
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:21:51 --> token is not a valid authenticator.
in VENDORPATH\codeigniter4\shield\src\Authentication\AuthenticationException.php on line 17.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(49): CodeIgniter\Shield\Authentication\AuthenticationException::forUnknownAuthenticator('token')
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(154): CodeIgniter\Shield\Authentication\Authentication->factory('token')
 3 APPPATH\Filters\CheckAuthFilter.php(29): CodeIgniter\Shield\Auth->__call('loggedIn', [])
 4 SYSTEMPATH\Filters\Filters.php(173): App\Filters\CheckAuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 5 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('api/v1/supplier/', 'before')
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:21:54 --> token is not a valid authenticator.
in VENDORPATH\codeigniter4\shield\src\Authentication\AuthenticationException.php on line 17.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(49): CodeIgniter\Shield\Authentication\AuthenticationException::forUnknownAuthenticator('token')
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(154): CodeIgniter\Shield\Authentication\Authentication->factory('token')
 3 APPPATH\Filters\CheckAuthFilter.php(29): CodeIgniter\Shield\Auth->__call('loggedIn', [])
 4 SYSTEMPATH\Filters\Filters.php(173): App\Filters\CheckAuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 5 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('api/v1/supplier/SP-00000000001', 'before')
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:22:07 --> token is not a valid authenticator.
in VENDORPATH\codeigniter4\shield\src\Authentication\AuthenticationException.php on line 17.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(49): CodeIgniter\Shield\Authentication\AuthenticationException::forUnknownAuthenticator('token')
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(154): CodeIgniter\Shield\Authentication\Authentication->factory('token')
 3 APPPATH\Filters\CheckAuthFilter.php(29): CodeIgniter\Shield\Auth->__call('loggedIn', [])
 4 SYSTEMPATH\Filters\Filters.php(173): App\Filters\CheckAuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 5 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('api/v1/supplier/SP-00000000001', 'before')
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:22:10 --> token is not a valid authenticator.
in VENDORPATH\codeigniter4\shield\src\Authentication\AuthenticationException.php on line 17.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(49): CodeIgniter\Shield\Authentication\AuthenticationException::forUnknownAuthenticator('token')
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(154): CodeIgniter\Shield\Authentication\Authentication->factory('token')
 3 APPPATH\Filters\CheckAuthFilter.php(29): CodeIgniter\Shield\Auth->__call('loggedIn', [])
 4 SYSTEMPATH\Filters\Filters.php(173): App\Filters\CheckAuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 5 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('api/v1/supplier/', 'before')
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:22:29 --> token is not a valid authenticator.
in VENDORPATH\codeigniter4\shield\src\Authentication\AuthenticationException.php on line 17.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(49): CodeIgniter\Shield\Authentication\AuthenticationException::forUnknownAuthenticator('token')
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(154): CodeIgniter\Shield\Authentication\Authentication->factory('token')
 3 APPPATH\Filters\CheckAuthFilter.php(29): CodeIgniter\Shield\Auth->__call('loggedIn', [])
 4 SYSTEMPATH\Filters\Filters.php(173): App\Filters\CheckAuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 5 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('api/v1/supplier/', 'before')
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:22:42 --> token is not a valid authenticator.
in VENDORPATH\codeigniter4\shield\src\Authentication\AuthenticationException.php on line 17.
 1 VENDORPATH\codeigniter4\shield\src\Authentication\Authentication.php(49): CodeIgniter\Shield\Authentication\AuthenticationException::forUnknownAuthenticator('token')
 2 VENDORPATH\codeigniter4\shield\src\Auth.php(154): CodeIgniter\Shield\Authentication\Authentication->factory('token')
 3 APPPATH\Filters\CheckAuthFilter.php(29): CodeIgniter\Shield\Auth->__call('loggedIn', [])
 4 SYSTEMPATH\Filters\Filters.php(173): App\Filters\CheckAuthFilter->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 5 SYSTEMPATH\CodeIgniter.php(431): CodeIgniter\Filters\Filters->run('api/v1/supplier/SP-00000000001', 'before')
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:23:07 --> Argument 1 passed to CodeIgniter\Shield\Entities\User::revokeAccessToken() must be of the type string, null given, called in D:\Developer\codeigniter4-erp-clg\app\Controllers\AuthController.php on line 86
in VENDORPATH\codeigniter4\shield\src\Authentication\Traits\HasAccessTokens.php on line 40.
 1 APPPATH\Controllers\AuthController.php(86): CodeIgniter\Shield\Entities\User->revokeAccessToken(null)
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->logout()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:26:35 --> Argument 1 passed to CodeIgniter\Shield\Entities\User::revokeAccessToken() must be of the type string, null given, called in D:\Developer\codeigniter4-erp-clg\app\Controllers\AuthController.php on line 86
in VENDORPATH\codeigniter4\shield\src\Authentication\Traits\HasAccessTokens.php on line 40.
 1 APPPATH\Controllers\AuthController.php(86): CodeIgniter\Shield\Entities\User->revokeAccessToken(null)
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->logout()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:27:25 --> Argument 1 passed to CodeIgniter\Shield\Entities\User::revokeAccessToken() must be of the type string, null given, called in D:\Developer\codeigniter4-erp-clg\app\Controllers\AuthController.php on line 86
in VENDORPATH\codeigniter4\shield\src\Authentication\Traits\HasAccessTokens.php on line 40.
 1 APPPATH\Controllers\AuthController.php(86): CodeIgniter\Shield\Entities\User->revokeAccessToken(null)
 2 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->logout()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:34:03 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('23', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058043.816864, 0.092, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:36:10 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('23', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058170.364345, 0.1044, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:36:15 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('24', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058175.189447, 0.0855, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:36:29 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('24', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058189.604339, 0.0887, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:36:43 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('25', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058203.225943, 0.0829, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:38:07 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('25', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058287.474011, 0.0898, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:39:11 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('28', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058351.558623, 0.0914, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:41:01 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('28', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058461.885897, 0.0869, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:41:11 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('29', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058470.989148, 0.0854, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:42:40 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('30', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(69): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 APPPATH\Controllers\AuthController.php(90): CodeIgniter\Shield\Auth->user()
10 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->logout()
11 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:42:52 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('31', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(69): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 APPPATH\Controllers\AuthController.php(90): CodeIgniter\Shield\Auth->user()
10 SYSTEMPATH\CodeIgniter.php(907): App\Controllers\AuthController->logout()
11 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:43:15 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('31', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058595.486177, 0.0854, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:47:15 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('34', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058835.036767, 0.0857, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:47:59 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('34', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058879.136645, 0.0859, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:48:26 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('34', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058906.198181, 0.0888, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:48:47 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('34', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058927.839444, 0.0852, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:49:05 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('34', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058944.932424, 0.084, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:49:26 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('35', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663058966.669555, 0.0847, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 15:52:36 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('35', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663059156.579938, 0.1182, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:10:50 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('39', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663060250.069996, 0.0836, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:11:31 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1596.
 1 SYSTEMPATH\BaseModel.php(1596): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(832): CodeIgniter\BaseModel->transformDataToArray([], 'update')
 3 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update([...], Object(CodeIgniter\Shield\Entities\AccessToken))
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->update('39', Object(CodeIgniter\Shield\Entities\AccessToken))
 5 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(128): CodeIgniter\BaseModel->save(Object(CodeIgniter\Shield\Entities\AccessToken))
 6 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(49): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->check([...])
 7 VENDORPATH\codeigniter4\shield\src\Authentication\Authenticators\AccessTokens.php(155): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->attempt([...])
 8 VENDORPATH\codeigniter4\shield\src\Auth.php(157): CodeIgniter\Shield\Authentication\Authenticators\AccessTokens->loggedIn()
 9 VENDORPATH\codeigniter4\shield\src\Collectors\Auth.php(65): CodeIgniter\Shield\Auth->__call('loggedIn', [])
10 SYSTEMPATH\Debug\Toolbar\Collectors\BaseCollector.php(222): CodeIgniter\Shield\Collectors\Auth->display()
11 SYSTEMPATH\Debug\Toolbar.php(93): CodeIgniter\Debug\Toolbar\Collectors\BaseCollector->getAsArray()
12 SYSTEMPATH\Debug\Toolbar.php(376): CodeIgniter\Debug\Toolbar->run(1663060291.809826, 0.0918, Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
13 SYSTEMPATH\Filters\DebugToolbar.php(40): CodeIgniter\Debug\Toolbar->prepare(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response))
14 SYSTEMPATH\Filters\Filters.php(196): CodeIgniter\Filters\DebugToolbar->after(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), null)
15 SYSTEMPATH\CodeIgniter.php(477): CodeIgniter\Filters\Filters->run('api/v1/logout', 'after')
16 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
17 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
18 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:36:03 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:36:07 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:36:11 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:36:12 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:36:29 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:36:39 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:37:04 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:37:37 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:38:29 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:38:31 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:38:32 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:38:33 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:38:33 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:38:33 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-09-13 16:38:34 --> Call to undefined function CodeIgniter\Shield\Controllers\auth()
in VENDORPATH\codeigniter4\shield\src\Controllers\RegisterController.php on line 30.
 1 SYSTEMPATH\CodeIgniter.php(907): CodeIgniter\Shield\Controllers\RegisterController->registerView()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\Shield\Controllers\RegisterController))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(73): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
